### PR TITLE
Fix negative component areas

### LINKED ISSUE #210: component areas negative when lat coordinate is reversed
When the latitude coordinate is reversed (going from +90 to -90, which is common in reanalyses), the component areas are negative.  The fix appears to be easy: adding `abs()` around the area in the summation.  I'll put in a PR on this momentarily.

@burlen and @elbashandy : I wonder if the test suite should include tests that all algorithms yield good results if latitude coordinates are reversed.

### PR DESCRIPTION
**Pull request by taobrienlbl**
Simple fix - adds `abs()` around area during summation.

Closes #210

### CODE REVIEW

File: alg/teca_2d_component_area.cxx [hunk 1]
```diff
@@ -94,7 +94,7 @@ void component_area(unsigned long nlon, unsigned long nlat,
         unsigned long jj = j*nlon;
         for (unsigned long i = 1; i < nlonm1; ++i)
         {
-            area[labels[jj + i]] += rho_sq_d_theta[i]*d_cos_phi_j;
+            area[labels[jj + i]] += abs(rho_sq_d_theta[i]*d_cos_phi_j);
```
Comment (burlen) [inline alg/teca_2d_component_area.cxx]: please use `std::abs`, depending on the header files included there are legacy integer only abs functions from ansi C library.

**Comment by taobrienlbl** [comment]
I just modified to use std::abs

> depending on the header files included there are legacy integer only abs functions from ansi C library.

@burlen and/or @elbashandy - could I please request that our CI tests be augmented to check for build success on platforms with such legacy headers?  It would be best if our automated testing caught such issues.

**Comment by burlen** [comment]
we should be able to improve our test coverage when #165 is complete.

In this case, if you did the headers wrong the build would fail. we are doing the headers correctly here. use of std:: namespace specifier is a one of those best practices that you just do.
