### PR TITLE
Closes #200 Support time dim integer

### LINKED ISSUE #200: support integer based time axis
ERA5 type data is not currently working(#177), time axis is integer, teca expected a floating point. Support read time values of any type.

Questions top answer before committing to a solution.
* how many algorithms would break if time was not a floating point type?
* does our calendaring assume time is a double? would it matter? eg passing single time values they can be converted without penalty.
* would it make more sense to always present time in double precision?

test data available in `/global/cscratch1/sd/taobrien/for_teca_data_svn`

```
$./bin/test/test_cf_reader "/work2/data/teca/for_teca_data_svn/ERA5/e5.*\.nc$" "test_cf_reader_%t%.%e%" "0" "-1" "longitude" "latitude" "." "time" "VIWVE"
ERROR: [0:140523024606976] [/home/bloring/work/teca/teca/io/teca_cf_reader.cxx:289 2.2.0]
ERROR: netcdf type code_ 4 is not a floating point type
ERROR: [0:140523024606976] [/home/bloring/work/teca/teca/io/teca_cf_reader.cxx:293 2.2.0]
ERROR: Failed to read variable "time" from "e5.oper.an.vinteg.162_071_viwve.regn320sc.20170217.nc". Unsupported data type
ERROR: [0:140522999428864] [/home/bloring/work/teca/teca/io/teca_cf_reader.cxx:289 2.2.0]
ERROR: netcdf type code_ 4 is not a floating point type
ERROR: [0:140522999428864] [/home/bloring/work/teca/teca/io/teca_cf_reader.cxx:293 2.2.0]
ERROR: Failed to read variable "time" from "e5.oper.an.vinteg.162_072_viwvn.regn320sc.20170217.nc". Unsupported data type
ERROR: [0:140523414570560] [/home/bloring/work/teca/teca/io/teca_cf_reader.cxx:768 2.2.0]
ERROR: Failed to read time axis
ERROR: [0:140523414570560] [/home/bloring/work/teca/teca/core/teca_index_executive.cxx:77 2.2.0]
ERROR: No index initializer key has been specified
ERROR: [0:140523414570560] [/home/bloring/work/teca/teca/core/teca_algorithm.cxx:686 2.2.0]
ERROR: failed to initialize the executive
ERROR: [0:140523414570560] [/home/bloring/work/teca/teca/core/teca_algorithm.cxx:710 2.2.0]
ERROR: failed to update port 0
```

contents of file
```
$ncdump -h /work2/data/teca/for_teca_data_svn/ERA5/e5.oper.an.vinteg.162_071_viwve.regn320sc.20170217.nc 
netcdf e5.oper.an.vinteg.162_071_viwve.regn320sc.20170217 {
dimensions:
	time = 4 ;
	latitude = 640 ;
	longitude = 1280 ;
variables:
	float VIWVE(time, latitude, longitude) ;
		VIWVE:_FillValue = 9.999e+20f ;
		VIWVE:long_name = "Vertical integral of eastward water vapour flux" ;
		VIWVE:short_name = "viwve" ;
		VIWVE:units = "kg m**-1 s**-1" ;
		VIWVE:original_format = "WMO GRIB 1 with ECMWF local table" ;
		VIWVE:ecmwf_local_table = 162 ;
		VIWVE:ecmwf_parameter = 71 ;
		VIWVE:grid_specification = "1280 longitude x 640 Gaussian latitude (0.281deg x ~0.281deg from 0E to 359.719E and 89.785N to 89.785S)" ;
		VIWVE:original_data_representation = "Reduced Gaussian grid (N320)" ;
		VIWVE:rda_dataset = "ds630.0" ;
		VIWVE:rda_dataset_url = "https:/rda.ucar.edu/datasets/ds630.0/" ;
		VIWVE:rda_dataset_doi = "DOI: 10.5065/D6X34W69" ;
		VIWVE:rda_dataset_group = "ERA5 atmospheric vertical integrals (ECMWF Table 162)" ;
		VIWVE:number_of_significant_digits = 7 ;
	double latitude(latitude) ;
		latitude:_FillValue = NaN ;
		latitude:long_name = "latitude" ;
		latitude:short_name = "lat" ;
		latitude:units = "degrees_north" ;
		latitude:qualifier = "Gaussian" ;
	double longitude(longitude) ;
		longitude:_FillValue = NaN ;
		longitude:long_name = "longitude" ;
		longitude:short_name = "lon" ;
		longitude:units = "degrees_east" ;
	int time(time) ;
		time:long_name = "time" ;
		time:units = "hours since 1900-01-01" ;
		time:calendar = "gregorian" ;
	int utc_date(time) ;
		utc_date:long_name = "UTC date yyyy-mm-dd hh:00:00 as yyyymmddhh" ;
		utc_date:units = "Gregorian_year month day hour" ;

// global attributes:
		:DATA_SOURCE = "ECMWF: ERA5 GRIB 1 spherical harmonics (T639) and reduced Gaussian grid data (N320)." ;
		:DATA_INTERPOLATION = "CISL RDA: ERA5 GRIB 1 N320/T639 data interpolated (or synthesized) to 1280 longitude x 640 Gaussian latitude GRIB 1 data using emoslib-4.3.9 (compiled with cmake with grib_api-1.14.7 and fftw-3.3.4 support for gnu/gfortran-4.4.7)." ;
		:NETCDF_CONVERSION = "CISL RDA: Conversion from interpolated/synthesized GRIB 1 data to netCDF4." ;
		:NETCDF_VERSION = "4.3.0" ;
		:CONVERSION_PLATFORM = "Linux geyser01 2.6.32-358.el6.x86_64 #1 SMP Wed Nov 2 11:00:18 MDT 2016 x86_64 x86_64 x86_64 GNU/Linux" ;
		:CONVERSION_DATE = "Mon Feb 12 17:38:07 MST 2018" ;
		:Conventions = "CF-1.6" ;
		:NETCDF_COMPRESSION = "NCO: Precision-preserving compression to netCDF4/HDF5 (see \"history\" and \"NCO\" global attributes below for specifics)." ;
		:history = "Mon Feb 12 17:39:18 2018: ncks -4 --ppc default=7 e5.oper.an.vinteg.162_071_viwve.regn320sc.2017020100_2017022823.unc.nc e5.oper.an.vinteg.162_071_viwve.regn320sc.2017020100_2017022823.nc" ;
		:NCO = "4.6.9" ;
}
```

### PR DESCRIPTION
**Pull request by elbashandy**

### CODE REVIEW

**Comment by burlen** [comment]
meed to be sure all cerr are removed, squash the commits, and add a regression test

**Comment by elbashandy** [comment]
@burlen I didn't squash the second commit as it was a good factor to consider when we were debugging how the code was segfaulting by adding 2 files with the same time values.

File: io/teca_cf_reader.cxx [hunk 1]
```diff
@@ -678,6 +656,7 @@ teca_metadata teca_cf_reader::get_output_metadata(
                     else
                     {
                         NC_DISPATCH(att_type,
+			  std::cerr << "att " << att_name << " " << att_len << std::endl;
```
Comment (burlen) [inline io/teca_cf_reader.cxx]: don't forget to clean this up

**Comment by burlen** [comment]
would you please squash these when done?

**Comment by elbashandy** [comment]
@burlen good point! Done :)

File: test/CMakeLists.txt [hunk 2]
```diff
@@ -58,6 +58,22 @@ teca_add_test(test_cf_reader
     FEATURES ${TECA_HAS_NETCDF}
     REQ_TECA_DATA)
 
+    teca_add_test(test_cf_reader_int_time
```
Comment (burlen) [inline test/CMakeLists.txt]: indentation is off here

File: io/teca_cf_reader.cxx [hunk 3]
```diff
@@ -284,10 +283,8 @@ class read_variable
                     << m_file << "\". " << nc_strerror(ierr))
                 return std::make_pair(m_id, nullptr);
             }
-            // success!
```
Comment (burlen) [inline io/teca_cf_reader.cxx]: don't remove comment

File: io/teca_cf_reader.cxx [hunk 4]
```diff
@@ -31,7 +31,6 @@ using std::cerr;
 #include <openssl/sha.h>
 #endif
 
-// macro to help with netcdf data types
```
Comment (burlen) [inline io/teca_cf_reader.cxx]: don't remove comment

File: io/teca_cf_reader.cxx [hunk 5]
```diff
@@ -284,10 +283,8 @@ class read_variable
                     << m_file << "\". " << nc_strerror(ierr))
                 return std::make_pair(m_id, nullptr);
             }
-            // success!
             return std::make_pair(m_id, var);
             )
-
```
Comment (burlen) [inline io/teca_cf_reader.cxx]: don't remove white space

File: io/teca_cf_reader.cxx [hunk 6]
```diff
@@ -287,7 +286,7 @@ class read_variable
             // success!
             return std::make_pair(m_id, var);
             )
-
+
```
Comment (burlen) [inline io/teca_cf_reader.cxx]: sorry to nitpick, but you added a line of spaces here rather than an empty line. does sublime support highlighting that? vim does, it makes it easy to catch.

File: io/teca_cf_reader.cxx (hunk 4 above)
Comment (elbashandy) [reply io/teca_cf_reader.cxx]: I don't remember removing any comment. you are right, they shouldn't be removed.

File: io/teca_cf_reader.cxx (hunk 6 above)
Comment (elbashandy) [reply io/teca_cf_reader.cxx]: Interesting! nice catch. another reason to use vim :)
